### ISSUE TITLE
[Feature] Allow the use of C-w to delete word during pattern input

### ISSUE THREAD

**Issue by jemag** [woosaaahh/sj.nvim#10]
A common workflow in Linux and vim, is to be able to delete the previous word using `C-W` while in insert mode. This does not seem possible currently when entering the search pattern:
![image](https://user-images.githubusercontent.com/7985687/193467209-69ea826a-3944-4d05-982c-0b805acf4790.png)

Although https://github.com/woosaaahh/sj.nvim/issues/9 could help, the current `C-U` keybind deletes the whole pattern, so the behavior would still be different.

This would be great for others, like me, who use `C-W` reflexively.

**Comment by woosaaahh** [comment]
My current issue with this feature is : what is a "word" ? _i.e._ what should I keep/delete ? 

The best compromise I've found is to use the "keywords" regex class : `[:keyword:]` (or `\k`).
The `Ctrl-w` builtin feature use `'iskeyword'` option to define what should be considered a keyword.

The code below is what I have so far that's close to (n)vim `Ctrl-w` feature.
The differences are due to how the `"` (double quotes) and `'` (single quotes) are handled.
 
I think it's simple and close enough to use this solution unless someone has a better one.

```lua
local text = [[vim.keymap.set({ "n", "o", "x" }, "S", function()]]
local ctrl_w_regex = [=[\v[[:keyword:]]\zs[^[:keyword:]]+$|[[:keyword:]]+$]=]

for _ = 1, #text do
	text = vim.fn.substitute(text, ctrl_w_regex, "", "")
	print(vim.inspect(text))

	if #text < 1 then
		break
	end
end

--- manual Ctrl+w in nvim
------------------------------------------------------
--- 'vim.keymap.set({ "n", "o", "x" }, "S", function'
--- 'vim.keymap.set({ "n", "o", "x" }, "S", '
--- 'vim.keymap.set({ "n", "o", "x" }, "S'
--- 'vim.keymap.set({ "n", "o", "x" }, "'
--- 'vim.keymap.set({ "n", "o", "x" }, '              <--- missing from ouput
--- 'vim.keymap.set({ "n", "o", "x" '                 <--- missing from ouput
--- 'vim.keymap.set({ "n", "o", "x'
--- 'vim.keymap.set({ "n", "o", "'
--- 'vim.keymap.set({ "n", "o", '                     <--- missing from ouput
--- 'vim.keymap.set({ "n", "o'
--- 'vim.keymap.set({ "n", "'
--- 'vim.keymap.set({ "n", '                          <--- missing from ouput
--- 'vim.keymap.set({ "n'
--- 'vim.keymap.set({ "'
--- "vim.keymap.set({ "                               <--- missing from ouput
--- "vim.keymap.set"
--- "vim.keymap."
--- "vim.keymap"
--- "vim."
--- "vim"
--- ""

--- script output
------------------------------------------------------
--- 'vim.keymap.set({ "n", "o", "x" }, "S", function'
--- 'vim.keymap.set({ "n", "o", "x" }, "S", '
--- 'vim.keymap.set({ "n", "o", "x" }, "S'
--- 'vim.keymap.set({ "n", "o", "x" }, "'
--- 'vim.keymap.set({ "n", "o", "x'
--- 'vim.keymap.set({ "n", "o", "'
--- 'vim.keymap.set({ "n", "o'
--- 'vim.keymap.set({ "n", "'
--- 'vim.keymap.set({ "n'
--- 'vim.keymap.set({ "'
--- "vim.keymap.set"
--- "vim.keymap."
--- "vim.keymap"
--- "vim."
--- "vim"
--- ""
```

**Comment by jemag** [comment]
I am terrible at regex so I cannot help much there.

Just throwing some ideas out there, another alternative could be to let the user write into a buffer of type `prompt`  (like in telescope.nvim) or to write directly to the `:` command and parsing that input (I believe this is the strategy used by vim-searchx), instead of grabbing each char then echoing it.

The advantage would be that both the prompt or the command area are subjects to regular vim behavior (although I think you have to bind `c-w` to `c-s-w` in prompt buffers). However there might be drawbacks to this strategy compared to the current mechanism, hard for me to gauge.

Otherwise, I am a bit surprised that there isn't a way to test vim normal or insert behavior on a string of text (applying insert mode `c-w` or something like `normal! bcw`). Haven't found a way so far, but perhaps others might know.

**Comment by woosaaahh** [comment]
I created a new discussion as a reply to your comment : https://github.com/woosaaahh/sj.nvim/discussions/11

**Comment by woosaaahh** [comment]
This is now provided by efb4b0c0307430aebf3f51ee92c1ad8fdc52f5dc

**Comment by woosaaahh** [comment]
Btw, `0.5` has been merged to `main`.
