### ISSUE TITLE
ui.lua:42: Invalid buffer id

### ISSUE THREAD

**Issue by jemag** [woosaaahh/sj.nvim#12]
**Versions used for**
 - Neovim: NVIM v0.9.0-dev-14-g085fa68b5
 - SJ.nvim : 082ab06be5d6c6a93afb3ca805cd0f67672b4e7a

**Describe the bug**
Doing a sj.run in some buffers and then closing them causes the following error:
![image](https://user-images.githubusercontent.com/7985687/194195520-3a4ef6f7-43ef-4ff0-82d0-b8bfdcfaf44c.png)

**To Reproduce**
Currently I can reproduce this behavior with buffers from 2 plugins : Neotree (https://github.com/nvim-neo-tree/neo-tree.nvim) and Neogit (https://github.com/TimUntersberger/neogit)

Here are the steps to reproduce with Neotree:
1. Open filesystem tree sidebar with `:Neotree filesystem focus toggle left`
2. Search a pattern with sj.run, e.g.: 
![image](https://user-images.githubusercontent.com/7985687/194195971-1e3dcf59-28c8-4e03-969d-c96e20f11992.png)
4. Close the Neotree filesystem sidebar using `:Neotree filesystem focus toggle left` again
5. Notice error
![image](https://user-images.githubusercontent.com/7985687/194196062-200117a2-1aa3-4b88-bba0-53ba3e93023b.png)

**Expected behavior**
No error is triggered

**Additional context**
Here is the sj.nvim config used:
```lua
local sj = require("sj")
sj.setup({
  auto_jump = false,
  separator = ";",
  -- help to better identify labels and matches
  use_overlay = false,
  preserve_highlights = true,
  search_scope = "buffer",
  update_search_register = true,
  relative_labels = true,
})
vim.keymap.set({ "n", "x", "o" }, "/", function()
  sj.run({
    prompt_prefix = "/",
  })
end)
vim.keymap.set({ "n", "x", "o" }, "?", function()
  sj.run({
    forward_search = false,
    prompt_prefix = "?",
  })
end)

```

**Comment by woosaaahh** [comment]
Thanks for the report !

This should be fixed by 0d00e70cb2096892e05171f1521ca5af06fe1305
