### ISSUE TITLE
No Highlights

### ISSUE THREAD

**Issue by johnallen3d** [woosaaahh/sj.nvim#2]
Thanks for this plugin, this is the first "jump" plugin I've seen that works with my muscle memory!

That said, I've noticed that I'm not seeing the searched text highlighted (like your image in README). I've tried enabling and disabling all of the 

Before activating `sj`:
<img width="340" alt="CleanShot 2022-09-16 at 10 04 05@2x" src="https://user-images.githubusercontent.com/184915/190657712-2679e682-4ec7-48a7-885d-0ded4d6513c4.png">

After:
<img width="339" alt="CleanShot 2022-09-16 at 10 04 52@2x" src="https://user-images.githubusercontent.com/184915/190657866-2aa03491-29fa-4af8-9b7a-18546ed96793.png">

**Comment by woosaaahh** [comment]
> Thanks for this plugin, this is the first "jump" plugin I've seen that works with my muscle memory!

Thanks a lot for your comment, I really appreciate reading this !
That's the main reason I made it.

In order to solve the issue quicker, could you please tell me 
- what version of the plugin do you use ?
- what is the output of the command below, if you run it with your config ?
`:highlight SjSearch`

**Comment by johnallen3d** [comment]
- latest version installed via Packer (`c0e2557`)
- commands output
    ```
    :highlight SjSearch
    SjSearch       xxx cleared
    :highlight SjOverlay
    SjOverlay      xxx cleared
    ```
- same issue with different colorscheme, yes (searching `local`)
<img width="185" alt="CleanShot 2022-09-16 at 18 02 34@2x" src="https://user-images.githubusercontent.com/184915/190810084-30053fdb-72c3-4516-a6a0-c8721ab8e8e8.png">

**Comment by woosaaahh** [comment]
According to this [great article](https://jdhao.github.io/2020/09/22/highlight_groups_cleared_in_nvim/), it seems that this is a problem with colorschemes that tend to clear highlights.

I'm pretty sure that if you run `:highlight IncSearch` (used by `SjSearch`) or `:highlight Comment` (used by `SjOverlay`), you'll get the same output as below.
```
:highlight IncSearch
IncSearch    xxx cleared
:highlight Comment
Comment      xxx cleared
```
The most common solution for cleared/overridden highlights is to use an autocommand to apply your own highlights when you switch colorschemes. You can find how to do this in the article.

I override colorschemes with an autocommand too in my configuration, that's probably why I didn't noticed this issue.

Here is what I use to override highlights : ( `Reload` is a custom function in my config but basically equivalent to `require("user.highlights")` )
```lua
vim.api.nvim_create_autocmd("ColorScheme", {
	pattern = "*",
	desc = "Override colorscheme rules.",
	callback = function()
		Reload("user.highlights")
	end,
})
```
---
I'm currently refactoring the whole plugin this week-end so I'll try to include a solution to prevent SJ highlights to be cleared but I also want the solution to let the user decide what to do. I'll figure it out !  ( big release maybe monday or tuesday ;p ) 

I'm not sure when the highlights are cleared in your config but in the meanwhile, maybe settings highlights in the configuration for SJ.nvim can help.

```lua
require("sj").setup({
	-- other 'sj' options if any
	-- ...

	highlights = {
		SjLabel = { fg = "#FFC080", bg = "#081321" },
		SjOverlay = { fg = "#345576" },
		SjSearch = { fg = "#55D0EE", bg = "#213455" },
		SjWarning = { fg = "#FF8060" },
		SjLimit = { fg = "#FF7090" },
	},
})
```

**Comment by johnallen3d** [comment]
Thanks for the thorough response @woosaaahh! I've managed to get it working thanks to your feedback! Here are the troubleshooting steps I took in case the extra data helps at all in your refactor.

- I tried using the highlights you provided in my typical setup and that didn't change anything.
- I checked `IncSearch` to see if it was `xxx cleared` as you expected but found this:
    ``` 
    :highlight IncSearch
    IncSearch      xxx guifg=#181825 guibg=#7ec9d8
    ```
- I tried loading a different colorscheme again (at startup vs after startup) but saw the same results.
- _Then_ I tried loading `sj` after startup (e.g. `require("my/sj_config")`) and it worked! I guess this is akin to using an autocommand as you described.

With that understanding, thanks to your input, I was able to update Packer to lazy-load `sj` (and my setup) after my colorscheme (`catppuccin`) and it works like a charm! 🎉

**Comment by woosaaahh** [comment]
I'm glad you solved your problem and I really appreciate you extra infos, it'll definitely help !
Thank you !

That said, users shouldn't have to change any configuration other than the one for SJ, to get this plugin working as expected... I must do better !
