### ISSUE TITLE
Jump "after" the selection

### ISSUE THREAD

**Issue by DrKGD** [woosaaahh/sj.nvim#26]
I was playing around with [nvim-surround](https://github.com/kylechui/nvim-surround) and I just noticed (after months of using sj.nvim by the way, duh!) that it is fully compatible as a motion.

Quoting the `README.md` example here
```lua
--- current line --------------------------------------

vim.keymap.set({ "n", "o", "x" }, "<localleader>l", function()
  sj.run({
    auto_jump = true,
    max_pattern_length = 1,
    pattern_type = "lua_plain",
    search_scope = "current_line",
    use_overlay = false,
  })
end)
```

This is the way I implemented it (legendary.nvim way of setting up the bindings, pretty much the same thing as above but with overlay enabled)
```lua
{ ';', mode = { 'n', 'o', 'x' }, function()
		last_target = 'sjsearch'
		require('sj').run({
			auto_jump = true,
			search_scope = 'current_line',
			max_pattern_length = 1,
			pattern_type = "lua_plain",
		})
	end, description = 'SJ on current line' }
```

At the moment, the binding kinda behaves like a 't' motion, thus stops exactly before the selected character.
I would like to setup a particular binding to behave just like the `f` motion group
Wanted behaviour

https://user-images.githubusercontent.com/44092476/210670607-47b9ee71-c713-4068-9a5d-ff4648ead3db.mp4

Current behaviour

https://user-images.githubusercontent.com/44092476/210670751-673005d5-9dec-4909-b0ad-33766dfd06f2.mp4

Would bring some advantages, thus extend the selection to exactly where I was planning to

https://user-images.githubusercontent.com/44092476/210671010-87d69c11-9a5c-4201-a423-3d14b77e01e9.mp4

Either this counts as a feature request, or I just got bamboozled by my reading skills, again :thinking:
Was thinking of using directly `vim.api.nvim_feedkeys('l', mode, true)` but it actually feeds the key to the `nvim-surround` plugin instead.

**Comment by woosaaahh** [comment]
Hi !

I'll be able to work on the plugin in the following days/weeks.
I'm really interested to add this feature.

For the record, I don't know if you heard but there is a new jump/search plugin in town : [flash.nvim](https://github.com/folke/flash.nvim)

**Comment by woosaaahh** [comment]
Hi !

The feature was added with 55556f134e5991d6ab10cb8e17161f19e1fc95c7.
For now, you can try it with the branch `0.7`.
There is a little explanation in the commit message and config examples in the README.

I close this issue but will reopen it if needed.

CC: @DrKGD

**Comment by DrKGD** [comment]
I'm terribly sorry, I did not have much time on my hands to test the lastest updates until~ now 🗿

I kinda forgot how to configure both of the plugins, and I am undergoing the "usual-routine" of rebuilding the entire nvim configuration from scratch, but from what I have seen until now it is working as expected with [mini.surround](https://github.com/echasnovski/mini.surround), which serves more or less the same functionalities from the one aforementioned.

And yes, I have also seen flash.nvim, did not test it yet, but after switching countless _search and jump plugins_, I kinda grew attached to sj and I am not considering to switch it out at all 👀

Thanks a lot!
