### ISSUE TITLE
Remove screenshot from repo

### ISSUE THREAD

**Issue by jemag** [woosaaahh/sj.nvim#4]
First of all, just wanted to say great job the on the plugin. Been playing around with it some more and really enjoying it. I was about to create an issue about the highlight and autocmd, but just realized that you fixed it already.

Anyway, just a small nitpick, but usually it is better to remove screenshots from the git repo, since users will be downloading it when adding the plugin through Packer. There are multiple ways to keep it in your README, simplest would be to just drag and drop your image while editing the README in the GitHub interface.

Thanks again for the plugin.

**Comment by woosaaahh** [comment]
> First of all, just wanted to say great job the on the plugin. Been playing around with it some more and really enjoying it. 
> Thanks again for the plugin.

Thanks a lot, I really appreciate reading this !

> it is better to remove screenshots from the git repo, since users will be downloading it when adding the plugin through Packer.

As I don't use Packer or any plugins manager, I never thought it could be a problem.

> There are multiple ways to keep it in your README, simplest would be to just drag and drop your image while editing the README in the GitHub interface.

Thanks for sharing this very simple solution ! 
I wasn't aware that GitHub can host files without having them in the repo.

Anyway, thanks again for your comment !
