### ISSUE TITLE
[Feature] Allow custom keybinds during pattern input

### ISSUE THREAD

**Issue by jemag** [woosaaahh/sj.nvim#9]
Currently, it seems that several of the keybinds used during pattern input are hardcoded. It would be nice to be able to customize those according to the user's preferences.

**Comment by woosaaahh** [comment]
I thought about it recently when I started implementing a page scroll while searching feature.
I didn't really knew what would be the best keymap and thought "at one point, it could be nice to let the user define them !".

Definitely a must have ! Thanks

**Comment by woosaaahh** [comment]
This is now provided by 538fb1982e23b80114f346d0ee0a91900ca71981.

**Comment by woosaaahh** [comment]
Btw, `0.5` has been merged to `main`.
